language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

after_script:
  - cargo doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh

env:
  global:
    - secure: st4RlsiafXRbnugESgPDRtrC94v2WeB6it1BjlanQBlacBa/HjPxKXySY3JaXcB4wk2ex9qGIR/Bqg7lzDGVQtwqRJ9mq4tWpdhE0yA1d/RZOuko6XbHyUPEjJAgUHUPuE7kokaAuOq3A+zh75k0SxBBHG+UBqwgUiPgqzGuEbaG5Zf5BnHwDi6rl2lFty6cf1JjYTj0und4pU6hk0uifcv4SN222kheNmv/uoP8mFKSgDPii72owSDB7eOQP2WURJ729qYI76USMTti0tb/eDHmi4QVAhasCSghsK/mD3l3Xcu90TmvuYYrkcyIHo7wOKT2LIRg5wK6qN0myKITHPVkoXwRnagl3nOsnymil9Kbybqad9Nxa20jYf/mBnbL125PDFKLczPH0SFP+qdmKZtBdL8DKYvSgHERPFSuU7YajJg3sEIXXNetReMOQIOPXt8G6lwD9u7eIeJYv+wHTrNDH5eoN3BuLBRdaB40cGqL5tSSLFcCgsUQy+dhV6HFqetoLiOIbChehJKlRvAQg1nLSlRgOl4Riw0dVroHsm+lCZW3caCIWSBol8UiEWy1od60mklLxmT46SbxvGvAu5b5IF4YqKTfQGrDgci+XNTl0a/RFlkfBhPQTMF74rF16S4w7CupDa6HXIS5cJKrq6YT921YhFcPCy+3PyO22AU=
