language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

after_script:
  - cargo doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh

env:
  global:
    - secure: tSctZqKKdzYNpIYBHHbFICsbjSCc0gW5XFjnfdGnwiOKvYZcG5O7unxEWcmvZZ7q1WfwV8qTDG4ZIZlZ+0wQPeGNwcpgiTyKc+2AGfnm0tbkFBiiHPAU6UFf232PLNW7PePTh8mcAEqZ9H43wjpUnOD3r+tUOa48lFoUPcBH0ZPzbRAouTlVc1FGh3bp5Gumk0EJAYGOyDn6pqgbdXtNuCLXgoZpIb9JQnCwg8aRDE5e3k5+fuRwR3u06sZTLSlUk/cIej+M+6YjB3BXKCJ2QA93Vbxr50I1dpzF6HZuTmggTtQfMMvcRE/+zAVzm/3O3GBN+rk75B+bczJ6flmcPGdBeasm9i/Y5DEOCNunyR72VswYlff9MOZIxR1TXsZReZvt3L9sAqny9JcU0UBYKsDoWrIDYYUpTBx6lmKOe4aG/mO/30UVKCoH3VNlKi1MNNwVLCWzgko1Gl0R2+lEfm4r1BQoqZ93WowlsZgvBIB+5pK/3r445hckCHzffwlFCd9zPUNdnGb3X0i//ly+eAvnR14RwiV94CSFsYuCWKXRubynNP5nqr21QYGIPM20E0w9sWuGInKtDaJNYnFM/6EuKEhmuEmXXxNZFvsD6EyoeCFC1vEiOt6rzt2fLTmzC2BbQjrQ5kocI5nqjZy8VAUIQfO16rzkyoODMMUNt/Q=
